[package]
name        = "Landespolizeidirektion Vorarlberg"
version     = "1.1.0"
edition     = "2026"
description = "Landespolizeidirektion Vorarlberg — Whiteboard"
authors     = ["Miriam Hanke <miriam@hankemacht.de>"]
license     = "Proprietary"
homepage    = "https://hankemacht.de"

[[bin]]
name = "landespolizeidirektion_vorarlberg"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri             = { version = "2", features = ["devtools"] }
tauri-plugin-dialog = "2"
tauri-plugin-fs     = "2"
serde               = { version = "1", features = ["derive"] }
serde_json          = "1"

[profile.release]
codegen-units = 1
lto           = true
opt-level     = "s"
panic         = "abort"
strip         = true
